from SOJ import db, create_app
from SOJ.models import *

a = create_app()

with a.app_context():
    db.drop_all()
    db.create_all()
    p1 = Problem(title="Sum of 2 numbers.", statement="Given x and y. Print x+y.", input="The only input line has a string of length x and y.", output="Print one integer: x+y", constraint="1≤n≤106", solved=0, tried=0, categories="Math")
    t1 = TestCases(prob_id=1, input="2 3\n", output="5\n")
    t2 = TestCases(prob_id=1, input="4 5\n", output="9\n")
    p2 = Problem(title="Sum of 3 numbers.", statement="Given x, y and z. Print x+y+z.", input="The only input line has a string of length x, y and z.", output="Print one integer: x+y+z", constraint="1≤n≤106", solved=0, tried=0, categories="Math")
    t3 = TestCases(prob_id=2, input="2 3 4\n", output="9\n")
    t4 = TestCases(prob_id=2, input="4 5 6\n", output="15\n")
    p3 = Problem(title="Difference", statement="Given x and y. Print x-y.", input="The only input line has a string of length x and y.", output="Print one integer: x-y", constraint="1≤n≤106", solved=0, tried=0, categories="Math")
    t5 = TestCases(prob_id=3, input="2 3\n", output="-1\n")
    t6 = TestCases(prob_id=3, input="4 5\n", output="-1\n")
    p4 = Problem(title="Connected Components", statement="Given a graph with n nodes and m edges. Print the number of connected components.", input="The first line contains two integers n and m. Each of the next m lines contains two integers u and v, meaning that there is an edge between nodes u and v.", output="Print one integer: the number of connected components.", constraint="1≤n≤106", solved=0, tried=0, categories="Graph")
    t7 = TestCases(prob_id=4, input="4 2\n1 2\n3 2\n", output="2\n")
    t8 = TestCases(prob_id=4, input="4 3\n1 2\n3 2\n4 3\n", output="1\n")
    p5 = Problem(title="Shortest Path", statement="Given a graph with n nodes and m edges. Print the shortest path from node 1 to node n.", input="The first line contains two integers n and m. Each of the next m lines contains three integers u, v and w, meaning that there is an edge between nodes u and v with weight w.", output="Print one integer: the shortest path from node 1 to node n.", constraint="1≤n≤106", solved=0, tried=0, categories="Graph")
    t9 = TestCases(prob_id=5, input="4 2\n1 2 1\n3 2 1\n", output="2\n")
    t10 = TestCases(prob_id=5, input="4 3\n1 2 1\n3 2 1\n4 3 1\n", output="1\n")
    db.session.add(p1)
    db.session.add(t1)
    db.session.add(t2)
    db.session.add(p2)
    db.session.add(t3)
    db.session.add(t4)
    db.session.add(p3)
    db.session.add(t5)
    db.session.add(t6)
    db.session.add(p4)
    db.session.add(t7)
    db.session.add(t8)
    db.session.add(p5)
    db.session.add(t9)
    db.session.add(t10)
    db.session.commit()